A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('error404/', TemplateView.as_view(template_name='404.html')),
    path('rosetta/', include('rosetta.urls')),
]

blog/urls.py
from django.urls import path

from blog import views


app_name = 'blog'
urlpatterns = [
    path('post/detail/<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/category/<slug:slug>/', views.PostCategoryView.as_view(), name='post-category'),
    path('post/search/', views.PostSearchView.as_view(), name='post-search'),
]

core/urls.py
from django.urls import path

from core import views


app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('newsletter/create/', views.NewsletterPartialView.as_view(), name='newsletter-create'),
]

templates/include/canvas_menu.html
{% load static %}

<div class="canvas-menu d-flex align-items-end flex-column">
    <!-- close button -->
    <button type="button" class="btn-close" aria-label="Close"></button>
    <!-- logo -->
    <div class="logo">
        <img src="{{ me.image_logo.url }}" alt="{{ me.get_fullname_en }}"/>
    </div>
    <!-- menu -->
    <nav>
        <ul class="vertical-menu">
            <li class="{% if request.path == '/' %}active{% endif %}">
                <a href="{% url 'core:home' %}">صفحه اصلی</a>
            </li>
            <li class="{% if request.path == '/contact/' %}active{% endif %}">
                <a href="{% url 'core:contact' %}">تماس با من</a>
            </li>
            <li class="{% if request.path == '/about/' %}active{% endif %}">
                <a href="{% url 'core:about' %}">درباره من</a>
            </li>
        </ul>
    </nav>
    <!-- social icons -->
    <ul class="social-icons list-unstyled list-inline mb-0 mt-auto w-100">
        <li class="list-inline-item">
            <a href="{{ me.facebook }}">
                <i class="fab fa-facebook-f"></i>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="{{ me.twitter }}">
                <i class="fab fa-twitter"></i>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="{{ me.instagram }}">
                <i class="fab fa-instagram"></i>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="{{ me.pinterest }}">
                <i class="fab fa-pinterest"></i>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="{{ me.youtube }}">
                <i class="fab fa-youtube"></i>
            </a>
        </li>
    </ul>
</div>

templates/include/footer.html
<footer>
    <div class="container-xl">
        <div class="footer-inner">
            <div class="row d-flex align-items-center gy-4">
                <!-- copyright text -->
                <div class="col-md-4">
                                <span class="copyright">
                                    طراحی شده توسط<a href="https://github.com/alireza-fa"> علیرضا فیضی</a>
                                </span>
                </div>
                <!-- social icons -->
                <div class="col-md-4 text-center">
                    <ul class="social-icons list-unstyled list-inline mb-0">
                        <li class="list-inline-item">
                            <a href="{{ me.facebook }}">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="{{ me.twitter }}">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="{{ me.instagram }}">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="{{ me.pinterest }}">
                                <i class="fab fa-pinterest"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="{{ me.youtube }}">
                                <i class="fab fa-youtube"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- go to top button -->
                <div class="col-md-4">
                    <a href="#" id="return-to-top" class="float-md-end">
                        <i class="icon-arrow-up"></i>
                        بازگشت به بالا
                    </a>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/include/header.html
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}">
<!-- STYLES -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'css/all.min.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'css/slick.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'css/simple-line-icons.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'css/vazir-font.css' %}" type="text/css" media="all">

templates/include/instagram_feed.html
{% load static %}

{% load sidebar_filter %}

<div class="instagram">
    <div class="container-xl">
        <!-- button -->
        <a href="{{ me.instagram }}" class="btn btn-default btn-instagram">@{{ me.instagram_id }} در اینستاگرام</a>
        <!-- images -->
        <div class="instagram-feed d-flex flex-wrap">
            {% for post in 'instagram_posts'|sidebar %}
            <div class="insta-item col-sm-2 col-6 col-md-2">
                <a>
                    <img src="{{ post.image.url }}" alt="{{ post.name }}"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/include/js.html
{% load static %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky-sidebar.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

templates/include/navbar_custom.html
{% load static %}

<div class="container-xl header-top">
    <div class="row align-items-center">
        <div class="col-4 d-none d-md-block d-lg-block">
            <!-- social icons -->
            <ul class="social-icons list-unstyled list-inline mb-0">
                <li class="list-inline-item">
                    <a href="{{ me.facebook }}">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="{{ me.twitter }}">
                        <i class="fab fa-twitter"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="{{ me.instagram }}">
                        <i class="fab fa-instagram"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="{{ me.pinterest }}">
                        <i class="fab fa-pinterest"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="{{ me.youtube }}">
                        <i class="fab fa-youtube"></i>
                    </a>
                </li>
            </ul>
        </div>
        <div class="col-md-4 col-sm-12 col-xs-12 text-center">
            <!-- site logo -->
            <a class="navbar-brand" href="{% url 'core:about' %}">
                <img src="{{ me.image_avatar2.url }}" alt="{{ me.get_fullname_en }}"/>
            </a>
            <a href="{% url 'core:about' %}" class="d-block text-logo">
                <span class="dot">.</span>
                Tina
            </a>
            <span class="slogan d-block">{{ me.position }}</span>
        </div>
        <div class="col-md-4 col-sm-12 col-xs-12">
            <!-- header buttons -->
            <div class="header-buttons float-md-end mt-4 mt-md-0">
                <button class="search icon-button">
                    <i class="icon-magnifier"></i>
                </button>
                <button class="burger-menu icon-button ms-2 float-end float-md-none">
                    <span class="burger-icon"></span>
                </button>
            </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-expand-lg">
    <div class="container-xl">
        <div class="collapse navbar-collapse justify-content-center centered-nav">
            <!-- menus -->
            <ul class="navbar-nav">
                <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'core:home' %}">صفحه اصلی</a>
                </li>
                <li class="nav-item {% if request.path == '/contact/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'core:contact' %}">تماس با من</a>
                </li>
                <li class="nav-item {% if request.path == '/about/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'core:about' %}">درباره من</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/include/navbar_default.html
<nav class="navbar navbar-expand-lg">
    <div class="container-xl">
        <!-- site logo -->
        <a class="navbar-brand" href="{% url 'core:home' %}"><img src="{{ me.image_logo.url }}" alt="{{ me.get_fullname_en }}"/></a>

        <div class="collapse navbar-collapse">
            <!-- menus -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'core:home' %}">صفحه اصلی</a>
                </li>
                <li class="nav-item {% if request.path == '/contact/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'core:contact' %}">تماس با من</a>
                </li>
                <li class="nav-item {% if request.path == '/about/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'core:about' %}">درباره من</a>
                </li>
            </ul>
        </div>

        <!-- header right section -->
        <div class="header-right">
            <!-- social icons -->
            <ul class="social-icons list-unstyled list-inline mb-0">
                <li class="list-inline-item"><a href="{{ me.facebook }}"><i class="fab fa-facebook-f"></i></a></li>
                <li class="list-inline-item"><a href="{{ me.twitter }}"><i class="fab fa-twitter"></i></a></li>
                <li class="list-inline-item"><a href="{{ me.instagram }}"><i class="fab fa-instagram"></i></a></li>
                <li class="list-inline-item"><a href="{{ me.pinterest }}"><i class="fab fa-pinterest"></i></a></li>
                <li class="list-inline-item"><a href="{{ me.youtube }}"><i class="fab fa-youtube"></i></a></li>
            </ul>
            <!-- header buttons -->
            <div class="header-buttons">
                <button class="search icon-button">
                    <i class="icon-magnifier"></i>
                </button>
                <button class="burger-menu icon-button">
                    <span class="burger-icon"></span>
                </button>
            </div>
        </div>
    </div>
</nav>

templates/include/newsletter.html
{% load static %}

<div class="widget rounded">
    <div class="widget-header text-center">
        <h3 class="widget-title">خبرنامه</h3>
        <img src="{% static 'images/wave.svg' %}" class="wave" alt="wave"/>
    </div>
    <div class="widget-content">
        <span class="newsletter-headline text-center mb-3">به ما بپیوندید!</span>
        <form action="{% url 'core:newsletter-create' %}" method="dialog" id="newsletter-form" novalidate>
            {% csrf_token %}
            <div class="mb-2">
                {{ news_form.news_email }}
            </div>
        </form>
        <button class="btn btn-default btn-full" id="newsletter-button">ثبت نام</button>
        <span class="newsletter-privacy text-center mt-3">
                                            با ثبت نام، با <a href="#">سیاست حفظ حریم خصوصی ما</a>
                                            موافقت می کنید
            </span>
    </div>
</div>
<br>

templates/include/search.html
<div class="search-popup">
    <!-- close button -->
    <button type="button" class="btn-close" aria-label="Close"></button>
    <!-- content -->
    <div class="search-content">
        <div class="text-center">
            <h3 class="mb-4 mt-0">ESC را فشار دهید تا بسته شود</h3>
        </div>
        <!-- form -->
        <form class="d-flex search-form" action="{% url 'blog:post-search' %}">
            <input class="form-control me-2" name="search" type="search" placeholder="جستجو کنید و اینتر را فشار دهید ..."
                   aria-label="Search">
            <button class="btn btn-default btn-lg" type="submit">
                <i class="icon-magnifier"></i>
            </button>
        </form>
    </div>
</div>

templates/include/sidebar.html
{% load static %}

{% load sidebar_filter %}

{% load datefilter %}

{% load render_partial %}

<div class="sidebar">
    <!-- widget about -->
    <div class="widget rounded">
        <div class="widget-about data-bg-image text-center"
             data-bg-image="{% static 'images/map-bg.png' %}">
            <img src="{{ me.image_logo.url }}" alt="Logo {{ me.get_fullname_en }}" class="mb-4"/>
            <p class="mb-4">{{ me.describe_short }}</p>
            <ul class="social-icons list-unstyled list-inline mb-0">
                <li class="list-inline-item">
                    <a href="{{ me.facebook }}">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="{{ me.twitter }}">
                        <i class="fab fa-twitter"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="{{ me.instagram }}">
                        <i class="fab fa-instagram"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="{{ me.pinterest }}">
                        <i class="fab fa-pinterest"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="{{ me.youtube }}">
                        <i class="fab fa-youtube"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <!-- widget مطالب جدید -->
    <div class="widget rounded">
        <div class="widget-header text-center">
            <h3 class="widget-title">مطالب جدید</h3>
            <img src="{% static 'images/wave.svg' %}" class="wave" alt="wave"/>
        </div>
        <div class="widget-content">
            {% for post in 'new_posts'|sidebar %}
            <!-- post -->
            <div class="post post-list-sm circle">
                <div class="thumb circle">
                    <span class="number">{{ forloop.counter }}</span>
                    <a href="{{ post.get_absolute_url }}">
                        <div class="inner">
                            <img src="{{ post.image_avatar.url }}" alt="{{ post.title_en }}"/>
                        </div>
                    </a>
                </div>
                <div class="details clearfix">
                    <h6 class="post-title my-0">
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </h6>
                    <ul class="meta list-inline mt-1 mb-0">
                        <li class="list-inline-item">{{ post.published_at|khayyam }}</li>
                    </ul>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <!-- widget categories -->
    <div class="widget rounded">
        <div class="widget-header text-center">
            <h3 class="widget-title">کاوش موضوعات</h3>
            <img src="{% static 'images/wave.svg' %}" class="wave" alt="wave"/>
        </div>
        <div class="widget-content">
            <ul class="list">
                {% for category in 'categories'|sidebar %}
                <li>
                    <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                    <span>({{ category.posts.count }})</span>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <!-- widget newsletter -->
    {% render_partial 'core.views.NewsletterPartialView' %}
</div>